FROM alpine:3.7

COPY . /go/src/github.com/gliderlabs/registrator
COPY ./makefile_dev.sh /usr/local/bin/

RUN /usr/local/bin/makefile_dev.sh

VOLUME ["/io"]

# systemd(1) likes to install itself as /sbin/init. On Ubuntu 20.04 this
# apparently happens *after* Dockerfile.0 finishes, unlike all previous Ubuntu
# versions. Let's just make our own init path that nothing else will touch.
RUN install -d -o0 -g0 -m0755 /container/
COPY init /container/
RUN chmod +x /container/init
ENTRYPOINT ["/container/init"]
CMD []
